name: mmimdb-xai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - h5py
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - pyyaml
  - pypdf
  - psutil
  - tqdm
  - ipykernel
  - pytorch
  - torchvision
  - cpuonly
  - pip:
      - iterative-stratification
      - captum
